version: 2.1

orbs:
  python: circleci/python@2.0.3
  black: iac/black@2.0.0

jobs:
  test_and_cover:
    docker:
      - image: cimg/python:3.10.4
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - run:
          command: |
            coverage run
            coverage report
            coverage html
          name: Testing
      - store_artifacts:
          path: htmlcov

workflows:
  testing:
    jobs:
      - test_and_cover
  black-format:
    jobs:
      - black/check
